// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"
)

type User struct {
	Username  string    `json:"username"`
	Password  []byte    `json:"password"`
	Salt      []byte    `json:"salt"`
	CreatedAt time.Time `json:"created_at"`
}
