// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

type User struct {
	Username  string `json:"username"`
	Password  []byte `json:"password"`
	Salt      []byte `json:"salt"`
	CreatedAt int64  `json:"created_at"`
}
