// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package storage

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE uid = ?
`

func (q *Queries) DeleteUser(ctx context.Context, uid string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, uid)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT uid, username, password, salt FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Uid,
			&i.Username,
			&i.Password,
			&i.Salt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByUid = `-- name: GetUserByUid :one
SELECT uid, username, password, salt FROM users WHERE uid = ?
`

func (q *Queries) GetUserByUid(ctx context.Context, uid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUid, uid)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Password,
		&i.Salt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT uid, username, password, salt FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.Uid,
		&i.Username,
		&i.Password,
		&i.Salt,
	)
	return i, err
}

const insertUser = `-- name: insertUser :exec
INSERT INTO users (uid, username, password, salt)
VALUES (?, ?, ?, ?)
`

type insertUserParams struct {
	Uid      string `json:"uid"`
	Username string `json:"username"`
	Password []byte `json:"password"`
	Salt     []byte `json:"salt"`
}

func (q *Queries) insertUser(ctx context.Context, arg insertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.Uid,
		arg.Username,
		arg.Password,
		arg.Salt,
	)
	return err
}

const updateUser = `-- name: updateUser :exec
UPDATE users SET username = ?, password = ?, salt = ? WHERE uid = ?
`

type updateUserParams struct {
	Username string `json:"username"`
	Password []byte `json:"password"`
	Salt     []byte `json:"salt"`
	Uid      string `json:"uid"`
}

func (q *Queries) updateUser(ctx context.Context, arg updateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Username,
		arg.Password,
		arg.Salt,
		arg.Uid,
	)
	return err
}
